hub:
  service:
    type: ClusterIP
    ports:
      nodePort:
  baseUrl: /
  cookieSecret:
  publicURL:
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  activeServerLimit:
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName: 
#      storageClassName: "nfs"
    url:
  labels: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /hub/metrics
  extraConfig: {}
  extraConfigMap: {}
#  extraEnv: {}
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']

  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  image:
    name: jupyterhub/k8s-hub
    tag: 36a8dcb
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  services: {}
  imagePullPolicy: IfNotPresent
  pdb:
    enabled: true
  networkPolicy:
    enabled: false
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


rbac:
  enabled: true


proxy:
#  secretToken: "6f1938382f3c5590fa18f406c3bb038efe99f8c1137b48291a6673513bd61877"
  secretToken: "dd059008b578a60b058725b74af50c7589300aab4ede45f5249a3b197355f181"
  service:
    type: NodePort
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 3.0.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.15.0
      pullPolicy: IfNotPresent
    proxyBodySize: 64m
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      tag: 0.1.6
    resources: {}
  labels:
  nodeSelector: {}
  pdb:
    enabled: true
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    hosts: []
  networkPolicy:
    enabled: false
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
      - supermap
      - openthings
  dummy:
    password:
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:


singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: 36a8dcb
  cloudMetadata:
    enabled: true
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    - ports:
      - port: 53
        protocol: UDP
    # Required egress is handled by other rules so it's safe to modify this
    #  - to:
    #      - ipBlock:
    #          cidr: 0.0.0.0/0
    #          except:
    #            - 169.254.169.254/32

  extraLabels: {}
  #extraEnv: {}
  extraEnv: 
    GRANT_SUDO: yes
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 100
  serviceAccountName:
  schedulerStrategy:
  storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    #static:
    #  pvcName:
    #  subPath: '{username}'
    capacity: 1Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:    
      #storageClass: "nfs"
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: openthings/databook
    tag: latest
    #name: jupyter/all-spark-notebook
    #tag: 5811dcb711ba
    # name: jupyterhub/k8s-singleuser-sample
    # tag: 36a8dcb
    pullPolicy: IfNotPresent
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"


prePuller:
  hook:
    enabled: true
    extraEnv: {}
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: 36a8dcb
  continuous:
    enabled: false
  extraImages: []
  pause:
    image:
      name: gcr.io/google_containers/pause
      tag: '3.0'


ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls:


cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
  podCuller:
    image:
      name: jupyterhub/k8s-pod-culler
      tag: 36a8dcb


debug:
  enabled: false
